/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/navbar/AppMenu.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    CustomDropDown: typeof import('./src/components/CustomDropDown.vue')['default']
    CustomDropzone: typeof import('./src/components/CustomDropzone.vue')['default']
    CustomFlatpicker: typeof import('./src/components/CustomFlatpicker.vue')['default']
    CustomGLightbox: typeof import('./src/components/CustomGLightbox.vue')['default']
    CustomStepper: typeof import('./src/components/CustomStepper.vue')['default']
    CustomStickyElement: typeof import('./src/components/CustomStickyElement.vue')['default']
    CustomTinySlider: typeof import('./src/components/CustomTinySlider.vue')['default']
    GuestAndRoomForm: typeof import('./src/components/GuestAndRoomForm.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/navbar/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/navbar/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/navbar/MenuItemWithChildren.vue')['default']
    MobileMenu: typeof import('./src/components/navbar/mobile-menu/MobileMenu.vue')['default']
    MobileMenuItem: typeof import('./src/components/navbar/mobile-menu/MobileMenuItem.vue')['default']
    MobileMenuItemLink: typeof import('./src/components/navbar/mobile-menu/MobileMenuItemLink.vue')['default']
    MobileMenuItemWithChildren: typeof import('./src/components/navbar/mobile-menu/MobileMenuItemWithChildren.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFormInput: typeof import('./src/components/SelectFormInput.vue')['default']
    VerticalMenu: typeof import('./src/components/navbar/mobile-menu/VerticalMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
    vBPopover: typeof import('bootstrap-vue-next')['vBPopover']
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
